version: "3"
services:
  db:
    build: ./db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres/tmp/data:/var/lib/postgresql/data
    restart: always
