version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01

    steps:
      - checkout

      - run:
          name: Set Environment Variables for docker-compose
          command: |
            set -x
            touch .env
            echo POSTGRES_USER=$POSTGRES_USER >> .env
            echo POSTGRES_PASSWORD=$POSTGRES_PASSWORD >> .env
            echo POSTGRES_DB=$POSTGRES_DB >> .env
            echo POSTGRES_PORT=$POSTGRES_PORT >> .env
            cat .env

      - run:
          name: Confirm directory state
          command: |
            set -x
            pwd && ls -a && ls db/

      - run:
          name: Build Docker container
          command: |
            set -x
            docker-compose build

      - run:
          name: Up Docker container
          command: |
            set -x
            docker-compose up -d
            docker-compose run --rm db sh -c "psql --version"
            docker-compose exec db bash
            psql --version
            psql -U postgres
            exit
            sleep 5
            docker ps -f status=running
            docker-compose logs

      - run:
          name: Down Docker container and Finish pipeline
          command: |
            set -x
            docker-compose down
            echo "Finish pipeline"
